sudo: required 
services: 
  - docker

 language: node_js  

 before_install:
   - docker build -t codecarl84/docker-react -f Dockerfile.dev . 


script:
  - docker run codecarl84/docker-react npm run test -- --coverage